### PR TITLE
Use interchange for some code paths

### PR DESCRIPTION
**Pull request by mattwthompson**

### CODE REVIEW

**Comment by richardjgowers** [comment]
@mattwthompson linting this is going to make it a nightmare to ever review.  If you really want to lint, can you lint only the touched lines?

**Comment by mattwthompson** [comment]
I've only ever had bad experiences with partial linting. Could you disable the bot in this repo and I'll just skip it?

**Comment by richardjgowers** [comment]
It's pretty safe to ignore the bot, @mikemhenry can you kill the bot with fire?

**Comment by mattwthompson** [comment]
Cleaner diff here https://github.com/mattwthompson/openfe_skunkworks/pull/2

**Pull request closed without merging**
